Self-hosted deb packages (#25)
* Self-hosted deb packages

* wip

* Fix downloading assets from release.

* Enables deploy to maven central from master.

Co-authored-by: Дамян Минков <damencho@jitsi.org>

diff --git a/.github/workflows/maven-and-native.yml b/.github/workflows/maven-and-native.yml
--- a/.github/workflows/maven-and-native.yml
+++ b/.github/workflows/maven-and-native.yml
@@ -2,13 +2,18 @@ name: Java and Natives
 
 on:
   push:
-    branches: [ master ]
-  pull_request:
-    branches: [ master ]
+    branches:
+      - master
+  #pull_request:
+  #  branches: [ master ]
 
 env:
   # Java version to use for the release
-  RELEASE_JAVA_VERSION: 8
+  RELEASE_JAVA_VERSION: 11
+
+concurrency:
+  group: ${{ github.ref }}
+  cancel-in-progress: true
 
 jobs:
   version:
@@ -16,17 +21,16 @@ jobs:
     runs-on: ubuntu-latest
     outputs:
       version: ${{ steps.version.outputs.version }}
-      deb_version: ${{ steps.version.outputs.deb_version }}
       create_tag: ${{ steps.version.outputs.create_tag }}
       tag_name: ${{ steps.version.outputs.tag_name }}
     steps:
       - name: Checkout
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
         with:
           fetch-depth: 0
 
       - name: Set up JDK
-        uses: actions/setup-java@v2
+        uses: actions/setup-java@v3
         with:
           java-version: ${{ env.RELEASE_JAVA_VERSION }}
           distribution: temurin
@@ -37,9 +41,9 @@ jobs:
         uses: actions/cache@v2
         with:
           path: ~/.m2/repository
-          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+          key: ${{ runner.os }}-maven-version-${{ hashFiles('**/pom.xml') }}
           restore-keys: |
-            ${{ runner.os }}-maven-
+            ${{ runner.os }}-maven-version-
 
       - name: Parse and set version
         id: version
@@ -50,9 +54,9 @@ jobs:
             if ! git rev-parse "$TAG_NAME" >/dev/null 2>&1
             then
               echo "Creating tag $TAG_NAME"
-              git config --local user.name "$GITHUB_ACTOR via GitHub Action"
-              git config --local user.email "action@github.com"
-              git tag -a "$TAG_NAME" -m "Tagged automatically by GitHub Action ${{ github.workflow }}"
+              git config --local user.name "$GITHUB_ACTOR via GitHub Actions"
+              git config --local user.email "actions@github.com"
+              git tag -a "$TAG_NAME" -m "Tagged automatically by GitHub Actions ${{ github.workflow }}"
               echo "::set-output name=create_tag::true"
             else
               echo "Tag: $TAG_NAME already exists"
@@ -60,16 +64,13 @@ jobs:
             fi
             VERSION=`git describe --match "v[0-9\.]*" --long --always`
             VERSION=${VERSION:1}
-            DEB_VERSION=${VERSION//-/.}
           else
             echo "Not on master"
             echo "::set-output name=create_tag::false"
             VERSION=${MVNVER}
-            DEB_VERSION=${VERSION//-/.}$(date -u +%s%3N)
           fi
           echo "Version: $VERSION"
           echo "::set-output name=version::${VERSION}"
-          echo "::set-output name=deb_version::${DEB_VERSION}"
           echo "::set-output name=tag_name::${TAG_NAME}"
 
   javatest:
@@ -77,14 +78,14 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        java: [ 8, 11, 17 ]
+        java: [ 11, 17 ]
 
     steps:
       - name: Checkout
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
 
       - name: Set up JDK ${{ matrix.java }}
-        uses: actions/setup-java@v2
+        uses: actions/setup-java@v3
         with:
           java-version: ${{ matrix.java }}
           distribution: temurin
@@ -93,16 +94,24 @@ jobs:
       - name: Build and test with Maven
         run: mvn -B verify -DperformRelease=true
 
+      - name: Upload JNI headers
+        if: matrix.java == env.RELEASE_JAVA_VERSION
+        uses: actions/upload-artifact@v3
+        with:
+          name: javah
+          path: target/native
+
   deb:
     runs-on: ubuntu-latest
-    needs: [ version, javatest ]
+    needs:
+      - version
+      - javatest
     strategy:
       fail-fast: false
       matrix:
         dist:
           - { vendor: ubuntu, dist: bionic }
           - { vendor: ubuntu, dist: focal }
-          - { vendor: ubuntu, dist: hirsute }
           - { vendor: ubuntu, dist: impish }
           - { vendor: ubuntu, dist: jammy }
           - { vendor: debian, dist: buster }
@@ -110,10 +119,10 @@ jobs:
         arch:
           - amd64
           - arm64
-          # pbuilder fails on ca-certificates-java
-          #- ppc64el
+          - ppc64el
         include: [
-          { dist: { vendor: ubuntu, dist: bionic }, arch: i386 },
+          # crossbuild-essential-i386 is missing on bionic, failing sbuild
+          # { dist: { vendor: ubuntu, dist: bionic }, arch: i386 },
           { dist: { vendor: debian, dist: buster }, arch: i386 },
           { dist: { vendor: debian, dist: bullseye }, arch: i386 },
         ]
@@ -122,103 +131,82 @@ jobs:
 
     env:
       UBUNTUTOOLS_UBUNTU_MIRROR: http://azure.archive.ubuntu.com/ubuntu
-      UBUNTUTOOLS_DEBIAN_MIRROR: http://deb.debian.org/debian
+      UBUNTUTOOLS_DEBIAN_MIRROR: http://debian-archive.trafficmanager.net/debian/
+      UBUNTUTOOLS_DEBSEC_MIRROR: http://debian-archive.trafficmanager.net/debian-security
+      DEBIAN_FRONTEND: noninteractive
 
     steps:
       - name: Checkout
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
         with:
           fetch-depth: 0
 
       - name: Install Java
-        uses: actions/setup-java@v2
+        uses: actions/setup-java@v3
         with:
           java-version: ${{ env.RELEASE_JAVA_VERSION }}
           distribution: temurin
           cache: maven
 
-      - name: Set Maven package version
-        run: |
-          mvn -B versions:set -DnewVersion=${{ needs.version.outputs.version }} -DgenerateBackupPoms=false
-
-      - name: Install dev packages
-        env:
-          DEBIAN_FRONTEND: noninteractive
-        run: |
-          sudo apt-get update -y
-          # dev-tools from backports because https://bugs.launchpad.net/ubuntu/+source/ubuntu-dev-tools/+bug/1916633
-          sudo apt-get install -y \
-            ubuntu-dev-tools/$(lsb_release -c -s)-backports \
-            python3-ubuntutools/$(lsb_release -c -s)-backports \
-            binutils \
-            pbuilder \
-            debootstrap \
-            debian-archive-keyring \
-            git-buildpackage
-
-      - name: Install additional dev packages
-        if: ${{ matrix.arch == 'arm64' || matrix.arch == 'ppc64el' }}
-        env:
-          DEBIAN_FRONTEND: noninteractive
-        run: |
-          # https://bugs.launchpad.net/ubuntu/+source/qemu/+bug/1895456
-          # https://gitlab.com/qemu-project/qemu/-/issues/588
-          sudo add-apt-repository ppa:canonical-server/server-backports
-          sudo apt-get update -y
-          sudo apt-get install -y qemu-user-static
-          # see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=904336 and https://bugs.launchpad.net/qemu/+bug/1594394
-          echo PBUILDERSATISFYDEPENDSCMD=/usr/lib/pbuilder/pbuilder-satisfydepends-apt >> ~/.pbuilderrc
-
-      - name: Cache pbuilder archive
-        uses: actions/cache@v2
-        id: deb_cache
+      - name: Get JNI headers
+        uses: actions/download-artifact@v3
         with:
-          path: ~/pbuilder/${{ matrix.dist.dist }}*-base.tgz
-          key: pbuilder-${{ matrix.dist.dist }}-${{ matrix.arch }}
+          name: javah
+          path: target/native
 
-      - name: Create or update pbuilder base
-        id: pbuilder_create
-        run: |
-          if [ "${{ steps.deb_cache.outputs.cache-hit }}" != "true" ]; then
-            pbuilder-dist ${{ matrix.dist.dist }} ${{ matrix.arch }} create
-          else
-            pbuilder-dist ${{ matrix.dist.dist }} ${{ matrix.arch }} update
-          fi;
-
-      - name: Build deb archive
+      - name: Import GPG key
         env:
           GPG_PASSPHRASE: "${{ secrets.GPG_PW }}"
         run: |
-          pbuilder_args=()
-          if [[ "${{ matrix.arch }}" != "amd64" ]]; then
-            pbuilder_args+=(--binary-arch)
-          fi;
           cat <(echo -e "${{ secrets.GPG_KEY }}") | gpg --batch --import
           gpg --list-secret-keys --keyid-format LONG
-          SINCE=$(git describe --match "v[0-9\.]*" --abbrev=0)
-          gbp dch \
-            --ignore-branch \
-            --since $SINCE \
-            --meta \
-            --release \
-            --distribution=${{ matrix.dist.dist }} \
-            --force-distribution \
-            --spawn-editor=never \
-            --new-version=${{ needs.version.outputs.deb_version }}~${{ matrix.dist.dist }}
-          dpkg-source -I.git -b .
-          pbuilder-dist ${{ matrix.dist.dist }} ${{ matrix.arch }} build \
-            --source-only-changes \
-            ${pbuilder_args[@]} \
-            --buildresult ~/pbuilder/${{ matrix.dist.vendor }}-${{ matrix.dist.dist }}-${{ matrix.arch }}_result \
-            ../jitsi-lgpl-dependencies_*.dsc
-          cd ~/pbuilder/${{ matrix.dist.vendor }}-${{ matrix.dist.dist }}-${{ matrix.arch }}_result
-          debsign -S -edev+maven@jitsi.org *_source.changes --re-sign -p${{ github.workspace }}/.github/workflows/gpg-wrap.sh
 
-      - name: Upload package as artifact
-        uses: actions/upload-artifact@v2
+      - name: Cache sbuild chroot stanza
+        uses: actions/cache@v2
+        id: chroot_cache
+        with:
+          path: target/chroot
+          key: chroot-${{ matrix.dist.dist }}-${{ matrix.arch }}-${{ hashFiles('target/chroot/**') }}
+          restore-keys: |
+            chroot-${{ matrix.dist.dist }}-${{ matrix.arch }}-
+
+      - name: Move chroot from cache
+        if: steps.chroot_cache.outputs.cache-hit
+        run: |
+          sudo mkdir -p /var/lib/schroot/tarballs/
+          sudo mkdir -p /etc/schroot/chroot.d/
+          sudo mv target/chroot/tarballs/* /var/lib/schroot/tarballs/
+          sudo mv target/chroot/chroot.d/* /etc/schroot/
+          sudo chown -R root:root /var/lib/schroot/tarballs/
+          sudo chown -R root:root /etc/schroot/chroot.d/
+
+      - name: Install tools
+        run: resources/deb-prepare.sh
+
+      - name: Build deb package
+        # the user executing sbuild needs to be in the group sbuild, a relogin is not possible here
+        # bionic doesn't have /bin and /usr/bin merged, thus /bin/bash
+        shell: /usr/bin/sg sbuild -c "/bin/bash -e {0}"
+        env:
+          GPG_PASSPHRASE: "${{ secrets.GPG_PW }}"
+        run: |
+          resources/deb-build.sh \
+            "${{ needs.version.outputs.version }}" \
+            "${{ matrix.dist.dist }}" \
+            "${{ matrix.arch }}"
+
+      - name: Upload packages as artifact
+        uses: actions/upload-artifact@v3
         with:
           name: ${{ matrix.dist.vendor }}-${{ matrix.dist.dist }}-${{ matrix.arch }}
-          path: ~/pbuilder/${{ matrix.dist.vendor }}-${{ matrix.dist.dist }}-${{ matrix.arch }}_result/*
+          path: target/debian/${{ matrix.dist.dist }}/*
+
+      - name: Archive chroot for cache
+        run: |
+          mkdir -p target/chroot
+          sudo mv /var/lib/schroot/tarballs/ target/chroot
+          sudo mv /etc/schroot/chroot.d/ target/chroot
+          sudo chown -R runner:runner target/chroot
 
   windows:
     name: Windows ${{ matrix.arch}} Natives
@@ -227,7 +215,9 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        arch: [ x86, x64 ]
+        arch:
+          #- x86
+          - x64
     steps:
       - name: Expand architecture
         id: expand_arch
@@ -244,19 +234,22 @@ jobs:
           fi;
 
       - name: Checkout
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
+
+      - name: Get JNI headers
+        uses: actions/download-artifact@v3
+        with:
+          name: javah
+          path: target/native
 
       - name: Install Java
         id: install_java
-        uses: actions/setup-java@v2
+        uses: actions/setup-java@v3
         with:
           java-version: ${{ env.RELEASE_JAVA_VERSION }}
           architecture: ${{ matrix.arch }}
           distribution: temurin
           cache: maven
-
-      - name: Compile Java for JNI headers
-        run: mvn -B compile
 
       - name: Install MSYS2 packages
         uses: msys2/setup-msys2@v2
@@ -280,7 +273,7 @@ jobs:
           cmake --build cmake-build-${{ matrix.arch}} --config Release --target install
 
       - name: Upload natives
-        uses: actions/upload-artifact@v2
+        uses: actions/upload-artifact@v3
         with:
           name: win32-${{ steps.expand_arch.outputs.jitsi_arch }}
           path: src/main/resources/win32-${{ steps.expand_arch.outputs.jitsi_arch }}/*
@@ -288,44 +281,59 @@ jobs:
   mac:
     runs-on: macos-latest
     needs: javatest
+    strategy:
+      fail-fast: false
+      matrix:
+        arch:
+          - x86_64
+          - arm64
     steps:
       - name: Checkout
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
+
+      - name: Get JNI headers
+        uses: actions/download-artifact@v3
+        with:
+          name: javah
+          path: target/native
 
       - name: Install Java
         id: install_java
-        uses: actions/setup-java@v2
+        uses: actions/setup-java@v3
         with:
+          distribution: zulu
           java-version: ${{ env.RELEASE_JAVA_VERSION }}
-          distribution: temurin
-          cache: maven
-
-      - name: Compile Java for JNI headers
-        run: mvn -B compile
+          architecture: ${{ matrix.arch }}
 
       - name: Build natives
         run: |
           brew install yasm
           brew install nasm
-          cmake -B cmake-build -DJAVA_HOME=${{ steps.install_java.outputs.path }}
-          cmake --build cmake-build --config Release --target install
+          curl https://raw.githubusercontent.com/FFmpeg/gas-preprocessor/898e8a7f573e22ada07f8db2b87e97078787db75/gas-preprocessor.pl --output ~/gas-preprocessor.pl
+          chmod +x ~/gas-preprocessor.pl
+          sudo mv ~/gas-preprocessor.pl /usr/local/bin/
+          resources/mac-cmake.sh ${{ steps.install_java.outputs.path }} ${{ matrix.arch }}
 
       - name: Upload natives
-        uses: actions/upload-artifact@v2
+        uses: actions/upload-artifact@v3
         with:
-          name: darwin
-          path: src/main/resources/darwin/*
+          name: darwin-${{ matrix.arch }}
+          path: src/main/resources/darwin-*/*
 
   release:
     if: github.ref == 'refs/heads/master'
-    needs: [ version, deb, windows, mac ]
+    needs:
+      - version
+      - deb
+      - windows
+      - mac
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
 
       - name: Set up JDK
-        uses: actions/setup-java@v2
+        uses: actions/setup-java@v3
         with:
           java-version: ${{ env.RELEASE_JAVA_VERSION }}
           distribution: temurin
@@ -334,38 +342,23 @@ jobs:
           server-username: SONATYPE_USER
           server-password: SONATYPE_PW
 
-      - name: Set version and prepare packages
-        id: version
-        run: |
-          sudo -H pip3 install --upgrade setuptools
-          sudo -H pip3 install --upgrade wheel
-          sudo -H pip3 install --upgrade cloudsmith-cli
-          sudo apt-get -y install dput
-          if [ "${{ needs.version.outputs.create_tag }}" == "true" ]; then
-            echo "Creating tag $TAG_NAME"
-            git config --local user.name "$GITHUB_ACTOR via GitHub Action"
-            git config --local user.email "action@github.com"
-            git tag -a "${{ needs.version.outputs.tag_name }}" -m "Tagged automatically by GitHub Action ${{ github.workflow }}"
-            git push origin "${{ needs.version.outputs.tag_name }}"
-          fi;
-          mvn -B versions:set -DnewVersion=${{ needs.version.outputs.version }} -DgenerateBackupPoms=false
-
       - name: Download binaries
-        uses: actions/download-artifact@v2
+        uses: actions/download-artifact@v3
         with:
           path: target
 
       - name: Copy natives for Maven
         run: |
-          ls -R
+          ls -aR
           BASEDIR=$(pwd)/src/main/resources
           mkdir -p $BASEDIR
           cd target
           for dist in */ ; do
-              mkdir $BASEDIR/$dist
               if [[ "$dist" =~ ^win32 ]]; then
+                  mkdir $BASEDIR/$dist
                   cp $dist/*.dll $BASEDIR/$dist
-              elif [[ "$dist" =~ darwin ]]; then
+              elif [[ "$dist" =~ ^mac ]]; then
+                  mkdir $BASEDIR/$dist
                   cp $dist/*.dylib $BASEDIR/$dist
               fi;
           done;
@@ -377,6 +370,7 @@ jobs:
         run: |
           cat <(echo -e "${{ secrets.GPG_KEY }}") | gpg --batch --import
           gpg --list-secret-keys --keyid-format LONG
+          mvn -B versions:set -DnewVersion=${{ needs.version.outputs.version }} -DgenerateBackupPoms=false
           mvn \
             --no-transfer-progress \
             --batch-mode \
@@ -387,29 +381,40 @@ jobs:
             -DskipTests \
             deploy
 
-      - name: Push packages to ppa and Cloudsmith
-        env:
-          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
+      - name: Pack all debs to avoid Github filename mangling
         run: |
-          REPO_NAME="jitsi-desktop-snapshots"
-          #if [ "${{ github.ref }}" == "refs/heads/master" ]; then
-          #  REPO_NAME="jitsi-desktop"
-          #fi;
-          cd target
-          for dist in */ ; do
-            if [[ "$dist" =~ ^(debian|ubuntu)- ]]; then
-              IFS='-' read -r -a triplet <<< "${dist/\//}"
-              # source only upload to ppa
-              if [[ "${triplet[0]}" == "ubuntu" && "${triplet[2]}" == "amd64" ]]; then
-                echo "Upload ${dist}*_source.changes to ppa:jitsi/$REPO_NAME"
-                dput ppa:jitsi/$REPO_NAME ${dist}*_source.changes
-              fi;
-              # upload all architecture-specific binaries to cloudsmith, but only one java-all
-              echo "Upload ${dist}libjitsi-lgpl-dependencies-jni_*.deb to Cloudsmith"
-              cloudsmith push deb jitsi/$REPO_NAME/${triplet[0]}/${triplet[1]} ${dist}libjitsi-lgpl-dependencies-jni_*.deb
-              if [[ "${triplet[2]}" == "amd64" ]]; then
-                echo "Upload ${dist}libjitsi-lgpl-dependencies-java_*.deb to Cloudsmith"
-                cloudsmith push deb jitsi/$REPO_NAME/${triplet[0]}/${triplet[1]} ${dist}libjitsi-lgpl-dependencies-java_*.deb
-              fi;
-            fi;
-          done;
+          tar -cvf debian-releases.tar target/{debian-*,ubuntu-*}/*
+
+      - name: Create release
+        uses: ncipollo/release-action@40bb172bd05f266cf9ba4ff965cb61e9ee5f6d01
+        with:
+          artifacts: "target/*.jar,debian-releases.tar"
+          allowUpdates: true
+          prerelease: true
+          draft: false
+          tag: r${{ needs.version.outputs.version }}
+          omitBody: true
+          removeArtifacts: true
+          replacesArtifacts: true
+          token: ${{ secrets.GITHUB_TOKEN }}
+          artifactErrorsFailBuild: true
+
+      - name: Tag
+        if: needs.version.outputs.create_tag == 'true'
+        run: |
+          git config --local user.name "$GITHUB_ACTOR via GitHub Actions"
+          git config --local user.email "actions@github.com"
+          git tag -a "${{ needs.version.outputs.tag_name }}" -m "Tagged automatically by GitHub Actions ${{ github.workflow }}"
+          git push origin "${{ needs.version.outputs.tag_name }}"
+
+  deploy:
+    name: Deploy Debian packages
+    needs:
+      - version
+      - release
+    uses: ./.github/workflows/deploy-debian.yml
+    with:
+      release_type: unstable
+      tag: r${{ needs.version.outputs.version }}
+    secrets:
+      APT_DESKTOP_REPO_UPLOAD: ${{ secrets.APT_DESKTOP_REPO_UPLOAD }}
